### ISSUE TITLE
The "crypto_api" path must be replaced with "concrete"

### ISSUE THREAD

**Issue by lupascucristian** [zama-ai/demo_z8z#5]
There are some errors due to the fact that the "crypto_api" path is no longer valid (see the open pull request for the fix):

<img width="712" alt="image" src="https://user-images.githubusercontent.com/32478719/122398748-d7506380-cf82-11eb-9b04-8f3131c98829.png">

**Comment by amyzx** [comment]
Hi, I have fixed this problem by replacing 
`use concrete::crypto_api` to `use concrete::*`
and replace all `crypto_api` by `concrete`

**Comment by lupascucristian** [comment]
Thanks @amyzx 🙏, I have already opened a pull request.

**Comment by amyzx** [comment]
@lupascucristian  By the way, I also find that `make test` doesn't work because in test.rs the following library cannot be found.
`use concrete::core_api::math::random`
I am trying to fix this problem, if you find the solution, please let me know. Thanks!

**Comment by amyzx** [comment]
@lupascucristian  
Hi, I have fixed the problem for `make test` by doing the following refactors in test.rs.
1. replace `use concrete::core_api::math::Random` with `use concrete_core::math::random`
2. replace line 13, 14 to line 15, 16 as shown in concrete/src/lib.rs, where you can find a function named `random_index`.

![image](https://user-images.githubusercontent.com/8285571/122523227-61fb9600-d049-11eb-9296-45ac9f440765.png)

**Comment by lupascucristian** [comment]
@amyzx, you should also open a pull request on the previous issue (the one for _make test_).
Thanks for the info 👍
